let Products = [
    {
      id: 1,
      name: "Product 1",
      description: "loren",
      price: 40,
      count: 0,
    },
    {
      id: 2,
      name: "Product 2",
      description: "loren",
      price: 60,
      count: 0,
    },
    {
      id: 3,
      name: "Product 3",
      description: "loren",
      price: 100,
      count: 0,
    },
    {
        id: 4,
        name: "Product 4",
        description: "loren",
        price: 40,
        count: 0,
      },
      {
        id: 5,
        name: "Product 5",
        description: "loren",
        price: 60,
        count: 0,
      },
      {
        id: 6,
        name: "Product 6",
        description: "loren",
        price: 100,
        count: 0,
      },
      {
        id: 7,
        name: "Product 7",
        description: "loren",
        price: 40,
        count: 0,
      },
      {
        id: 8,
        name: "Product 8",
        description: "loren",
        price: 60,
        count: 0,
      },
      {
        id: 9,
        name: "Product 9",
        description: "loren",
        price: 100,
        count: 0,
      },
      {
        id: 10,
        name: "Product 10",
        description: "loren",
        price: 40,
        count: 0,
      },
      {
        id: 11,
        name: "Product 11",
        description: "loren",
        price: 60,
        count: 0,
      },
      {
        id: 12,
        name: "Product 12",
        description: "loren",
        price: 100,
        count: 0,
      },
  ];
export default Products